### ISSUE TITLE
dwi support

### ISSUE THREAD

**Issue by activatedvoxel** [harvard-nrg/yaxil#20]
I was able to get it to download dti data, sort of, using: 
func:
  dwi:
    - scan: 21
      run: 1
      id: dti_1

But is shows up within the func directory, when I think it should have it's own dwi directory at the same level as func.

**Comment by tokeefe** [comment]
Until a few moments ago `ArcGet.py` didn't support `dwi` scans, but I just committed some preliminary support in the `dwi` branch

```bash
git clone -b dwi --single-branch https://github.com/harvard-nrg/yaxil.git
```
 
If you or someone from your team wants to give that a try and provide feedback, that would be super helpful. Or, if anyone wants to take a stab at fleshing out the implementation, here's where all the DWI specific processing happens

https://github.com/harvard-nrg/yaxil/blob/dwi/yaxil/bids/__init__.py#L195

As for the reason why your `dwi` scan was appearing under the `func` directory, that's because you had this in your configuration file

```yaml
func:
  dwi:
    - scan: N
      run: N
      ...
```

Which `ArcGet.py` interpreted as "`dwi` is a subtype of `func`"... which of course it isn't. If YAXIL was smart enough, it would have thrown an error message and refused to proceed (adding schema validation is on my long list of todos). But with the new `dwi` support, your configuration file should look something like this

```yaml
anat:
  T1w:
    - scan: 15
      run: 1
func:
  bold:
    - scan: 16
      run: 1
dwi:
  dwi:
    - scan: 26
      run: 1
```

and that should get you some/most of the way there. If you're wondering why there's a redundant `dwi` under `dwi`, that's how the BIDS specification is written. The two supported types of `dwi` at the moment are `dwi` and `sbref`.
